### ISSUE TITLE
Add tags for SPM

### ISSUE THREAD

**Issue by simonmcl** [hewigovens/wallet-core-spm#3]
@hewigovens  The swift package was updated a few days ago, because I have to use this pointing to the master branch instead of a release,  my CI auto pulled the latest which has a breaking change (init is now optional) causing build failures.

Can you tag the commits so we can point to specific releases?

**Comment by simonmcl** [comment]
FYI theres also a warning in my test bundle when using the latest, that it was specifically built for iOS 14.4 simulator. My target is iOS 14 and its having an issue with that. I think walletcore has a minimum of 12. It should probably be built for a simulator of the minimum support for walletcore to avoid issues

**Comment by hewigovens** [comment]
this repo is test only, please use latest from http://github.com/trustwallet/wallet-core, regarding the minimum deployment warning, please set  minimum deployment on Xcode project setting not each target
